Updated lando config to support XDebug 3 version
wunderio/drupal-project pull request #176
Opened 2021-01-08 09:04 UTC by mitrpaka

This PR adds support for Xdebug 3 version as PHP 7.2+ uses Xdebug 3.

Updates are based on info provided in the following lando related issue (and tested with Omnia lando setup):
https://github.com/lando/lando/issues/2718
https://github.com/lando/lando/pull/2741/files

With these updates you are able switch xdebug on and off with existing tool commands of `lando xdebug-on` and `lando xdebug-off` as previously with Xdebug 2.

2021-01-08 10:57 UTC, tormi reviewed
Nice work! I'd add the XDebug launch code for VSCode as well as we already have `.vscode` folder in place.

2021-01-08 11:22 UTC, tormi approved these changes

2021-01-08 12:05 UTC, tormi requested changes
The `XDEBUG_MODE` envvar (https://xdebug.org/docs/all_settings#mode) in `.lando.yml` needs to be configured, we should probably document this.

2021-01-08 12:09 UTC, tormi requested changes
Looks like there's duplicate `xdebug.mode` defined in `php.ini` & `.lando.yml`.

2021-01-08 12:15 UTC, mitrpaka commented
> Looks like there's duplicate `xdebug.mode` defined in `php.ini` & `.lando.yml`.

Yes, and was intentional. XDEBUG_MODE: needs to be overriden in services and xdebug.mode defined in php.ini. Unless environment variable is not overriden, it will be set as XDEBUG_MODE: off by default. (Tested it)

2021-01-08 12:21 UTC, misterjoonas commented on .lando.yml
> +        XDEBUG_MODE:
Is this empty on purpose?

2021-01-11 06:45 UTC, misterjoonas commented on .vscode/launch.json
> +    }
We have this also in a project which allows VSCode to open the currently running script:
```
{
      "name": "Launch currently open script",
      "type": "php",
      "request": "launch",
      "program": "${file}",
      "cwd": "${fileDirname}",
      "port": 9003
    }

```

2021-01-29 14:00 UTC, tormi requested changes

2021-01-29 14:00 UTC, tormi commented on .lando.yml
> +        XDEBUG_MODE:
`XDEBUG_MODE` is mapped to `xdebug` key value in `.lando.yml`: `XDEBUG_MODE: (options.xdebug === false) ? 'off' : options.xdebug,`. Also, `if (options.xdebug === true) options.xdebug = 'debug';`.

Source: https://github.com/lando/lando/blob/master/plugins/lando-services/services/php/builder.js#L147-L158

2021-01-29 20:47 UTC, tormi commented
Conversation at Lando Slack channel: https://devwithlando.slack.com/archives/C2XBSHX8R/p1611945598083900

2021-01-29 23:20 UTC, tormi commented
Okay, I have `lando xdebug <mode>` tool working:

`.lando.yml`:
```
config:
  xdebug: off
services:
  appserver:
    overrides:
      environment:
        XDEBUG_MODE:
tooling:
  xdebug:
    description: Defines Xdebug mode(s).
    cmd: 
      - appserver: /app/.lando/xdebug.sh
```

`/app/.lando/xdebug.sh`:
```
#!/bin/bash

if [ "$#" -ne 1 ]; then
  mode=debug
else
  mode="$1"
fi

docker-php-ext-enable xdebug
echo xdebug.mode = "$mode" > /usr/local/etc/php/conf.d/zzz-lando-my-custom.ini
pkill -o -USR2 php-fpm
```

Usage: `lando xdebug <mode>`.  `lando xdebug` only is using `debug` mode as default.

The problem is that only `/usr/local/etc/php/conf.d/zzz-lando-my-custom.ini` can be used here and there might be other stuff in place already via
```
config:
  config:
    php: php.ini
```
which gets overridden.

@pirog, your advice would be really appreciated here ;)

2021-01-30 00:16 UTC, tormi commented
Okay, did some changes to `xdebug.sh` - it appends xdebug.mode to the *.ini file now and removes the previous entries:

```
#!/bin/bash

if [ "$#" -ne 1 ]; then
  mode=debug
else
  mode="$1"
fi

docker-php-ext-enable xdebug
awk '!/xdebug.mode/' /usr/local/etc/php/conf.d/zzz-lando-my-custom.ini
echo xdebug.mode = "$mode" | tee -a /usr/local/etc/php/conf.d/zzz-lando-my-custom.ini
pkill -o -USR2 php-fpm
```

2021-01-30 09:57 UTC, tormi commented
Continued here to get some more attention: https://github.com/lando/lando/issues/1668#issuecomment-770186410

2021-01-30 11:32 UTC, tormi approved these changes

2021-01-30 11:33 UTC, merged

2021-02-03 19:48 UTC, tormi commented
That's why we're setting an empty `XDEBUG_MODE` envvar with this PR: https://github.com/lando/lando/issues/2728#issuecomment-739988384